"""
Batch-fit all 13,608 BW25113 chemical-media growth curves with KinBiont aHPM.

FitOptions mirror the GUIbiont web interface defaults:
  smooth=true, smooth_method=:rolling_avg, smooth_pt_avg=14
  cut_stationary_phase=true, stationary_percentile_thr=0.05
  stationary_pt_smooth_derivative=10, stationary_win_size=5, loss="RE"

Each curve is fitted on its own valid (non-missing) timepoints — conditions differ
in measurement duration (44–97 timepoints), so GrowthData is constructed per curve.

Run with multiple threads for speed:
  julia --threads auto batch_fit.jl

Input:  data/Round0{1-7}.csv   (generated by preprocess.py)
Output: results/batch_fit_results.csv

Columns: round, label, gr, exit_lag_rate, N_max, shape, aicc, loss, n_timepoints, converged
"""

using Pkg
Pkg.activate(@__DIR__)

using Kinbiont
using CSV
using DataFrames
using Statistics: mean, median

const DATA_DIR    = joinpath(@__DIR__, "data")
const RESULTS_DIR = joinpath(@__DIR__, "results")

# FitOptions matching GUIbiont interface
const OPTS = FitOptions(
    smooth                          = true,
    smooth_method                   = :rolling_avg,
    smooth_pt_avg                   = 14,
    cut_stationary_phase            = true,
    stationary_percentile_thr       = 0.05,
    stationary_pt_smooth_derivative = 10,
    stationary_win_size             = 5,
    loss                            = "RE",
)

const _AHPM     = MODEL_REGISTRY["aHPM"]
const _N_PARAMS  = length(_AHPM.param_names)   # 4: gr, exit_lag_rate, N_max, shape
const SPEC = ModelSpec(
    [_AHPM],
    [fill(1.0, _N_PARAMS)];
    lower = [fill(0.0,  _N_PARAMS)],
    upper = [fill(50.0, _N_PARAMS)],
)

# ---------------------------------------------------------------------------
# Per-curve GrowthData from a raw CSV DataFrame
# ---------------------------------------------------------------------------

"""
    curve_data(raw, label) -> GrowthData

Extract a single-curve `GrowthData` from the raw CSV DataFrame, keeping only
timepoints where the curve has a non-missing OD value.
"""
function curve_data(raw::DataFrame, label::String)::GrowthData
    times_all = Float64.(raw[!, :Time_h])
    od_col    = raw[!, Symbol(label)]
    mask      = .!ismissing.(od_col)
    times     = times_all[mask]
    od        = Float64.(od_col[mask])
    curves    = reshape(od, 1, length(od))
    return GrowthData(curves, times, [label])
end

# ---------------------------------------------------------------------------
# Fit one round — fully parallel across curves
# ---------------------------------------------------------------------------

"""
    fit_round(round_num) -> DataFrame

Load the CSV for `round_num`, then fit each curve in parallel using
`Threads.@threads`. Each curve uses only its own valid (non-missing) timepoints.
"""
function fit_round(round_num::Int)::DataFrame
    csv_path = joinpath(DATA_DIR, "Round$(lpad(round_num, 2, '0')).csv")
    raw      = CSV.read(csv_path, DataFrame; missingstring="")
    labels   = string.(names(raw)[2:end])   # skip Time_h
    n        = length(labels)
    println("  Round$(lpad(round_num, 2, '0')): $(n) curves on $(Threads.nthreads()) thread(s) … ")

    results = Vector{Any}(undef, n)
    Threads.@threads for i in 1:n
        label = labels[i]
        try
            data = curve_data(raw, label)
            res  = kinbiont_fit(data, SPEC, OPTS)
            r    = res[1]
            p    = Float64.(r.best_params)
            results[i] = (
                round         = round_num,
                label         = label,
                gr            = p[1],
                exit_lag_rate = p[2],
                N_max         = p[3],
                shape         = p[4],
                aicc          = r.best_aic,
                loss          = r.loss,
                n_timepoints  = length(data.times),
                converged     = true,
            )
        catch
            results[i] = (
                round         = round_num,
                label         = label,
                gr            = NaN,
                exit_lag_rate = NaN,
                N_max         = NaN,
                shape         = NaN,
                aicc          = NaN,
                loss          = NaN,
                n_timepoints  = 0,
                converged     = false,
            )
        end
    end

    df    = DataFrame(results)
    n_ok  = sum(df.converged)
    println("    done  (converged: $(n_ok)/$(n))")
    return df
end

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

function main()
    mkpath(RESULTS_DIR)
    println("Threads: $(Threads.nthreads())")
    println("Fitting rounds 1–7 with aHPM …\n")

    all_rounds = map(1:7) do r
        fit_round(r)
    end
    results = vcat(all_rounds...)

    out_path = joinpath(RESULTS_DIR, "batch_fit_results.csv")
    CSV.write(out_path, results)
    println("\nSaved $(nrow(results)) rows → $(out_path)")

    conv = filter(r -> r.converged, results)
    pct  = round(100 * nrow(conv) / nrow(results); digits=1)
    println("\nConverged: $(nrow(conv))/$(nrow(results)) ($(pct)%)")
    println("\nParameter summary (converged curves):")
    for col in [:gr, :exit_lag_rate, :N_max, :shape]
        vals = filter(!isnan, conv[!, col])
        isempty(vals) && continue
        μ   = round(mean(vals);   sigdigits=3)
        med = round(median(vals); sigdigits=3)
        println("  $(rpad(string(col), 16))  mean=$(μ)  median=$(med)")
    end
end

main()
